export const COLOUR_BRAND = "#cb862b"
export const COLOUR_SECONDARY = "#5781CB"
export const COLOUR_DARK = "#282927"
export const COLOUR_SUBTLE = "#184240"
export const COLOUR_ACCENT = "#A1A1A1"
export const COLOUR_LIGHT = "#F4F4F4"

export const COLOUR_DAT_BLUE1 = "#4E79A7"
export const COLOUR_DAT_BLUE2 = "#789AC0"
export const COLOUR_DAT_BLUE3 = "#A5BCD5"
export const COLOUR_DAT_BLUE4 = "#D2DDEA"

export const COLOUR_DAT_ORANGE1 = "#F28E2C"
export const COLOUR_DAT_ORANGE2 = "#F5AA61"
export const COLOUR_DAT_ORANGE3 = "#F9C796"
export const COLOUR_DAT_ORANGE4 = "#FCE3CA"

export const COLOUR_DAT_RED1 = "#E15759"
export const COLOUR_DAT_RED2 = "#E98182"
export const COLOUR_DAT_RED3 = "#F0ABAC"
export const COLOUR_DAT_RED4 = "#F8D5D5"

export const COLOUR_DAT_GREEN1 = "#76B7B2"
export const COLOUR_DAT_GREEN2 = "#98C9C5"
export const COLOUR_DAT_GREEN3 = "#BBDBD9"
export const COLOUR_DAT_GREEN4 = "#DDEDEC"